name: 'Test Action'
description: 'Test Action'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}

    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install CBR Website Beta (from PIP)
      shell: bash
      run: |
        python --version
        if [ -n "$VERSION" ]; then
          echo "Installing CBR Website Beta version: $VERSION"
          pip install cbr_website_beta==$VERSION
        else
        echo "Installing latest CBR Website Beta from pip" 
          pip install cbr_website_beta
        fi
        pip list

    - name: Update CBR Content (from git repo)
      uses: ./.github/actions/update-cbr-content

    - name: Copy custom code to Python site-packages
      shell: bash
      run: |        
        export python_packages=$(python -c "import site; print(site.getsitepackages()[0])")
        echo "Copying custom code to: $python_packages" 
        cp -R $CBR__CUSTOM__PATH_CUSTOM_CODE/* $python_packages

    - name: Run script to update S3 and Lambda (on custom CBR)
      shell: bash
      run: |
        export CBR__CUSTOM__VERSION_FILE=$S3_DEV__VERSION
        export CBR__CUSTOM__LAMBDA_NAME=$S3_DEV__VERSION
        export PYTHONPATH=/tmp

        echo "****** UPDATING S3 with current custom code ******"
        export python_packages=$(python -c "import site; print(site.getsitepackages()[0])")

        cbr_website_beta=$python_packages/cbr_website_beta

        python__publish_to_s3=${cbr_website_beta}/utils/update_from_s3/CBR__Publish_To_S3__Custom_Version.py
        python__create_lambda=${cbr_website_beta}/utils/update_from_s3/CBR__Custom__Deploy_Lambda.py

        python $python__publish_to_s3
        python $python__create_lambda
        echo "###################################"
        echo "##### Deployment complete     #####"
        echo "###################################"
        
