name: 'Update CBR Content'
description: 'Update CBR Content'

runs:
  using: 'composite'
  steps:

    - name: clone repo
      shell: bash
      run: |                        
        python_path=/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages
        python_path__cbr_content=$python_path/cbr_content
        tmp_folder=/tmp        
                        
        cd $tmp_folder
        git clone --branch dev https://github.com/the-cyber-boardroom/cbr-content.git /tmp/cbr-content
                
        cp -R $tmp_folder/cbr-content/cbr_content/* $python_path__cbr_content        
        
