name: 'Update CBR Content'
description: 'Test Action'

runs:
  using: 'composite'
  steps:

    - name: clone repo
      shell: bash
      run: |                        
        python_path=/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages        

        tmp_folder=/tmp
        python_path__cbr_content=$python_path/cbr_content                

        cd $tmp_folder
        git clone https://github.com/the-cyber-boardroom/cbr-content.git /tmp
        
        ls $tmp_folder
        ls $tmp_folder/cbr-content
        ls $tmp_folder/cbr-content/cbr_content
        
        cp -R $tmp_folder/cbr-content/cbr_content/* $python_path__cbr_content
        find $python_path__cbr_content
        
