name: 'deploy-cbr-git-site'
description: 'deploy-cbr-git-site'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}

    - name: Install dependencies from git
      shell: bash
      run: |
        tmp_folder=/tmp                                
        cd $tmp_folder
        ls -la
        git clone --branch dev https://github.com/the-cyber-boardroom/cbr-content.git
        git clone --branch dev https://github.com/the-cyber-boardroom/cbr-static.git
        git clone --branch dev https://github.com/the-cyber-boardroom/cbr-web-components.git
        git clone --branch dev https://github.com/the-cyber-boardroom/cbr-website-beta.git
        git clone --branch dev https://github.com/the-cyber-boardroom/cbr-athena.git
        ls -la