name: 'deploy-cbr-git-site'
description: 'deploy-cbr-git-site'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}

    - name: Install dependencies from git
      shell: bash
      run: |
        pwd
        ls -la
        git clone --branch dev https://github.com/the-cyber-boardroom/cbr-content.git 
        ls -la