name       : CI Pipeline - DEV
on:
  workflow_dispatch:
  repository_dispatch:
    types: [ deploy-community-dev ]
  push:
    branches:
      - dev

env:
  GIT__BRANCH                     : 'dev'
  PACKAGE_NAME                    : 'cbr_community'
  AWS_ACCESS_KEY_ID               : ${{ secrets.AWS_ACCESS_KEY_ID__470426667096     }}
  AWS_SECRET_ACCESS_KEY           : ${{ secrets.AWS_SECRET_ACCESS_KEY__470426667096 }}
  CBR__CONFIG_FILE                : 'cbr-website.community-cbr-hosted.toml'
  CBR__CUSTOM__ACCOUNT_ID         : '654654216424'
  AWS_REGION                      : eu-west-1
  CBR__CUSTOM__PATH_CUSTOM_CODE   : "./cbr_community/custom"
  CBR__CUSTOM__PACKAGES_TO_INSTALL: '["cbr_website_beta", "cbr_static", "cbr_content", "cbr_web_components", "cbr_shared", "cbr_athena"]'
  S3_DEV__BUCKET                  : "654654216424--cbr-deploy--eu-west-1"
  S3_DEV__PARENT_FOLDER           : "cbr-custom-websites"

jobs:

  wait-for-pypi-publish:
    name: Wait for PYPI Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wait_for_pip_package
        uses: ./.github/actions/wait_for_pip_package
        env:
          VERSION: ${{ github.event.client_payload.version }}

  deploy-cbr-community-dev:
    timeout-minutes: 5
    name: "Deploy CBR - Community"
    runs-on: ubuntu-latest
    env:
      S3_DEV__VERSION   : 'dev__custom-version__cbr_community'
      FOLDER__CBR_CUSTOM: "./cbr_community"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT__BRANCH }}
      - name: Deploy Custom code
        uses: ./.github/actions/deploy-cbr-dev-site
        env:
          VERSION: ${{ github.event.client_payload.version }}
    needs:
      - wait-for-pypi-publish